### ISSUE TITLE
Redirect partly working

### ISSUE THREAD

**Issue by ulysse-lacour** [dgrebb/strapi-dashbored#1]
Hi, first of all thank you for you code and article it was really good learning material and very clear instructions!

I know you're already aware of the fact the redirect is only partially working, did you find any solution on this ?

**Comment by ulysse-lacour** [comment]
I found a solution ! It requires to use patch-package and update `node_modules/@strapi/admin/admin/src/pages/HomePage/index.js` with 

```js
// Import at top
import { Redirect } from 'react-router-dom';

// replace return value of HomePageCE
return <Redirect to={'/plugins/dashbored'} />;
```

You're then always redirected to your custom dashboard!

**Comment by dgrebb** [comment]
@ulysse-lacour you are the best! I'll look into including this with a commented out 'postinstall' in 'package.json'. 

I've been digging into the routing system, and doing this the "plugin" way, but this is a great next step.

Thank you!

**Comment by ulysse-lacour** [comment]
Hey, I don't have a single clue on what is that postinstall script doing I just added it by following patch-package doc you think it's not needed ? Didn't manually triggered it that's for sure, I'd love to kick it out of here or at least understand what it does

I've upload my repo with the working version of custom homepage based on your work, quick readme too, if you wannna have a look : [PLUGIN](https://github.com/Lacour-Ulysse/Nuxt-x-Strapi-boilerplate/tree/main/strapi/src/plugins/dashbored)

The last thing I really need to do is find a way to not display dashbored in the left menu, ideally only for editor roles, if you have any idea let me know!

Thanks again for the article and code, lemme know if I can be of any help on your repo!
